### PR TITLE
Remove {CBC,COIN}_HAS_CLP checks

### LINKED ISSUE #612: build error on src/CbcHeuristicDive.cpp / code questions:
Hello all, 

I build on Ubuntu 22.04.2 LTS. I build release CoinMP-1.7.6, but the code in question seems to be the same compared to the latest release.

I get for some reason following error:

> CbcHeuristicDive.cpp: In member function 'int CbcHeuristicDive::solution(double&, int&, int&, OsiRowCut**, CbcSubProblem**&, double*)':
> CbcHeuristicDive.cpp:706:34: error: 'clpSolver' was not declared in this scope; did you mean 'solver'?
>   706 |           ClpSimplex * simplex = clpSolver->getModelPtr();
>       |                                  ^~~~~~~~~

Checking for the definition of the code I stumble on:

https://github.com/coin-or/Cbc/blob/d4272be8c5e3b231f35e7555587e427a5f69d1ed/src/CbcHeuristicDive.cpp#L299C8-L299C8

this #if clause does not make much sense to me.
If CBC_HAS_CLP is not defined the code breaks wich above error I assume.
So this is clause must have an else statement, at least an error statement. 
I wonder:
**1) What is the purpose of line 299?**

If I coment the macro if clause out, I get the following error message:

> 
> CbcHeuristicDive.cpp: In member function 'int CbcHeuristicDive::solution(double&, int&, int&, OsiRowCut**, CbcSubProblem**&, double*)':
> CbcHeuristicDive.cpp:215:7: error: cannot 'dynamic_cast' 'solver' (of type 'class OsiSolverInterface*') to type 'class OsiClpSolverInterface*' (target is not pointer or reference to complete type)
>   215 |     = dynamic_cast<OsiClpSolverInterface *> (solver);
>       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CbcHeuristicDive.cpp:217:42: error: invalid use of incomplete type 'class OsiClpSolverInterface'
>   217 |       ClpSimplex * clpSimplex = clpSolver->getModelPtr();
>       |                                          ^~

note: line 215 == 301 today

I am not sure what to do with this error. 
**2) why do we need to cast from OsiSolverInterface to OsiClpSolverInterface?**
Why is OsiClpSolverInterface not a child of OsiSolverInterface? (did not compare both classes, I am unsure if i can read your desicion from the code)

Thanks for your time, and efforts.

### PR DESCRIPTION
**Pull request by a-andre**
Cbc depends on Clp and doesn't compile without it.

Closes/Fixes #612.

### CODE REVIEW

**Comment by svigerske** [comment]
It was Ted who claimed in #612 that building Cbc with LP solvers other than CLP has been abandoned. I'm not against that, but maybe @jjhforrest wants to chime in as well.

**Comment by jjhforrest** [comment]
Does not really affect me at present.  If we had CBC_MUST_USE_CLP then one might be able to slowly make code marginally more efficient by changing solver_ to be OsiClpSolverInterface.  At present there are many many tests to see if solver_ is OsiClp...

**Comment by tkralphs** [comment]
This is fine with me. Even if someone wants to eventually try again to replace Clp as the solver for LP relaxations, it may still be difficult to remove all dependencies on Clp everywhere, os it will probably always be needed. It is also not really a burden to just  require it. Every way of installing it that I know of makes it easy to also install Clp at the same time. We should just make sure that configuration fails if Clp is not present.

**Comment by tkralphs** [comment]
Indeed, configuration should fail if Clp is not present.

**Comment by a-andre** [comment]
> Indeed, configuration should fail if Clp is not present.

This is done here https://github.com/coin-or/Cbc/blob/4e825eeb94bbe19a367e638471faab453d29efa2/configure.ac#L59-L64

Is there anything else left to do?
