### ISSUE TITLE
Usage of `pthread_getcpuclockid` on MacOS (stable/2.10)

### ISSUE THREAD

**Issue by Dekker1** [coin-or/Cbc#268]
I have a continuous build of CBC for MiniZinc, which I noticed stopped working in the last update to the stable/2.10 branch. It seems that the build uses a new pthread library function; however, this library function does not seem to be available on MacOS:
```
cbc/src/Cbc/src/CbcCutGenerator.cpp:283:2: error: use of undeclared identifier 'pthread_getcpuclockid'
```
I was hoping the usage of this function could be avoided or otherwise at least rewritten for MacOS

Versions:
- Apple clang version 11.0.0 (clang-1100.0.33.8)
- Xcode 11.0
